name: Build


on:
  workflow_dispatch:
    inputs:
      GITHUB_VERSIONING:
        description: "Version for Github Releases"
        required: true
        type: string
        default: "1.0.0"
      BUILD_WITH_DEBUG:
        description: "Build with Debug symbols"
        required: true
        type: boolean
        default: false




jobs:
  build:
    name: "Building the App (Windows)"
    runs-on: windows-2022
    permissions:
      contents: write
      packages: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
          
      - name: Build
        run: |
          if [[ "${{ inputs.BUILD_WITH_DEBUG }}" == "true" ]]; then
            cmd /c build.bat debug
          else
            cmd /c build.bat release
          fi

      - name: Upload to Github Releases
        uses: softprops/action-gh-release@v2
        with: 
          files: |
             build/ensemble
          name: Ensemble Release ${{ github.event.inputs.GITHUB_VERSIONING }}
          tag: ${{ github.event.inputs.GITHUB_VERSIONING }}  
          body: |
            Ensemble Release<br>
            Version ${{github.event.inputs.GITHUB_VERSIONING}}

            Notes:
            This release is for Windows only, find the Linux variant somewhere in this repo or build it yourself.
            
            For more information, visit: https://github.com/Mizumo-prjkt/ensemble
        env:
          GITHUB_TOKEN:  ${{secrets.KEYS}}
        
    